"use strict";

/**
 * @format
 * @type {{NetworkEvents: Readonly<{}>}}
 */
module.exports = Object.freeze({
  EVENT_NONE: 0,
  EVENT_UNIX_TIME_PREPARE: 50,
  EVENT_UNIX_TIME_API_CALL: 100,
  EVENT_UNIX_TIME_STATUS_CALLBACK: 200,
  EVENT_UNIX_TIME_RECEIVED_ON_REGION_DID: 300,
  EVENT_UNIX_TIME_RECEVIED_ON_PHYSICAL_DEVICE: 400,
  EVENT_UNIX_TIME_COMMUNICATION_FAILURE: 500,
  EVENT_UNIX_TIME_GENERAL_FAILURE: 600
});